# Generated by Django 3.0.3 on 2020-08-29 13:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200829_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 29, 13, 11, 10, 249282, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 29, 13, 11, 10, 249282, tzinfo=utc)),
        ),
    ]
