# Generated by Django 3.0.3 on 2020-08-30 09:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usergroups', '0001_initial'),
        ('projects', '0011_auto_20200829_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='usergroups.Usergroup'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 9, 9, 55, 880847, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 9, 9, 55, 880847, tzinfo=utc)),
        ),
    ]
